version: v2beta1

name: hodei-jobs

# Note: No 'images' section - we use binary sync instead of docker builds
# Image is managed by Helm via values-dev.yaml (tag: "dev")

pipelines:
  dev:
    run: |-
      create_deployments --all
      start_dev app

deployments:
  hodei:
    updateImageTags: true
    helm:
      chart:
        name: ./deploy/hodei-jobs-platform
      values:
        image:
          repository: localhost:5000/hodei-jobs-server
          tag: "dev"
          pullPolicy: Always
      valuesFiles:
        - ./deploy/hodei-jobs-platform/values.yaml
        - ./deploy/hodei-jobs-platform/values-dev.yaml

dev:
  app:
    # devImage: "" prevents DevSpace from replacing the container image
    devImage: "localhost:5000/hodei-jobs-server:dev"

    # Select the pod via labelSelector
    labelSelector:
      app.kubernetes.io/name: hodei-jobs-platform
      app.kubernetes.io/component: server
    # Sync configuration
    sync:
      - path: ./:/app
        excludePaths:
          - target/
          - .git/
          - .idea/
          - .vscode/
          - .cargo/

    # Port forwarding
    ports:
      - port: 9090:9090

    # Log streaming
    logs:
      enabled: true

    # Terminal
    terminal:
      command: /app/scripts/devspace-start.sh
