version: v2beta1

name: hodei-jobs

# Note: No 'images' section - we use binary sync instead of docker builds
# Image is managed by Helm via values-dev.yaml (tag: "dev")

pipelines:
  dev:
    run: |-
      create_deployments --all
      start_dev app

deployments:
  hodei:
    updateImageTags: true
    helm:
      chart:
        name: ./deploy/hodei-jobs-platform
      values:
        image:
          repository: registry.local:31500/hodei-jobs-server
          tag: "dev"
          pullPolicy: Never
        resources:
          limits:
            cpu: "8"
            memory: "12Gi"
          requests:
            cpu: "6"
            memory: "8Gi"
        # Enable DevSpace mode for cargo cache PVC
        development:
          enabled: true
          devspace:
            enabled: true
        volumes:
          extra:
            - name: cargo-cache
              persistentVolumeClaim:
                claimName: hodei-cargo-cache
        volumeMounts:
          - name: cargo-cache
            mountPath: /root/.cargo/registry
      valuesFiles:
        - ./deploy/hodei-jobs-platform/values.yaml
        - ./deploy/hodei-jobs-platform/values-dev.yaml

dev:
  app:
    devImage: 10.43.54.80:5000/hodei-jobs-server:dev

    # Select the pod via labelSelector
    labelSelector:
      app.kubernetes.io/name: hodei-jobs-platform
      app.kubernetes.io/component: server

    # Sync configuration - optimized for speed
    sync:
      - path: ./:/app
        # Prefer local files over container files
        initialSync: preferLocal
        # Exclude large non-productive paths from sync
        uploadExcludePaths:
          # Rust build artifacts (12GB+ - huge!)
          - target/
          - build/
          - Cargo.lock

          # Git metadata
          - .git/
          - .git/**/*

          # IDE cache
          - .idea/
          - .vscode/
          - "*.swp"
          - "*.swo"

          # Documentation (not needed in pod)
          - docs/
          - "*.md"
          - "!README.md"

          # Tests and benchmarks
          - "**/tests/"
          - "**/*_test.rs"
          - benches/
          - examples/

          # Generated/procduced files
          - proto/target/
          - "proto/*.rs"
          - .cargo/
          - "**/*.o"
          - "**/*.a"

          # Config files (mounted via ConfigMaps)
          - config.yaml
          - config/
          - "!config/*.example.*"

          # Database migrations (mounted)
          - migrations/
          - infrastructure-migrations/
          - "*.sql"

          # Logs and temp
          - logs/
          - "*.log"
          - tmp/
          - temp/

          # Monitoring (mounted separately)
          - monitoring/
          - prometheus/

          # Web/frontend (built separately)
          - web/
          - frontend/
          - client/

          # CI/CD
          - .github/
          - .gitlab-ci.yml

          # Coverage and profiling
          - coverage/
          - "*.profraw"
          - "*.profdata"

          # Special paths that break sync
          - "**/..data*"
          - "**/.ansible*"
          - "**/.*.swp"

    # Port forwarding
    ports:
      - port: 9090:9090

    # Log streaming
    logs:
      enabled: true

    # Terminal
    terminal:
      command: /app/scripts/devspace-start.sh
